config/routes.rb
Rails.application.routes.draw do



  resources :charges, only: [:new, :create, :update]

  resources :wikis

  resources :collaborators, only: [:create, :destroy]




# name of the controller(usually plural form of resource + controller)
  resources :registration_downgrades, only: [:create]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators

  has_many :users, through: :collaborators

# immediately after initialization, now when I save
# , since i need to check attribute private before it's saved
  after_initialize {self.private ||= false}
  # before_save {self.private ||= true}

    # validation : use ACTIVERECORD (every model inherits from it)
    validates :title, length: { minimum: 5 }, presence: true
    validates :body, length: { minimum: 20 }, presence: true
    validates :user, presence: true


end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  #  an after_find and after_initialize callback is triggered
  #  for each object that is found and instantiated by a finder,
  # with after_initialize being triggered after new objects are instantiated as well.

  before_action :authorize_sign_in, except: [:show, :index]

  def index
    # shwo authorized wikis based on role of user

    @wikis = policy_scope(Wiki)
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    authorize_private_wiki if @wiki.private

# will present errors if faile
    if @wiki.save
      flash[:notice] = "Successfully created a wiki."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error: could not create wiki."
      render :new
    #  test if you can redirect
    end

  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize_private_wiki if @wiki.private

  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize_private_wiki if @wiki.private

  end

  def update
    @wiki = Wiki.find(params[:id])

    @wiki.assign_attributes(wiki_params)

    authorize_private_wiki if @wiki.private

    if policy(@wiki).update? && @wiki.save
      flash[:notice] = "Successfully updated wiki."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error: could not update wiki. Must own wiki."
      render :edit
    end

  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if policy(@wiki).update? && @wiki.destroy
      flash[:notice] = "Successfully deleted wiki."
      redirect_to wikis_path
    else
      flash[:alert] = "Error: could not delete wiki. Must own wiki."
      redirect_to wikis_path
    end
  end


  private

  # used to mass assign params(from forms) and create/update wiki
  def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
  end

  def authorize_private_wiki
    unless (current_user.admin? || current_user.premium?)
      flash[:alert] = "You must be a premium user to create a private wiki."
      redirect_to :back
    end
  end


  def authorize_sign_in
    unless current_user
      redirect_to new_user_session_path
    end
  end

end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>

<!-- DOES THIS FIRE ONLY AFTER SUBMISSION? -->
 <% if wiki.errors.any? %>
   <div class="alert alert-danger">
     <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>

     <ul>
       <% wiki.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>

   </div>
 <% end %>
<!-- CREATE FORM AND DISPLAY AN ERRROR ONLY IF THERE IS AN ERRY FOR THE wiki ATTRIBUTE -->

  <%= form_group_tag(wiki.errors[:title]) do %>
     <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>

<!-- WHERE ARE THE ERRORS OF THESE BEING DISPLAYED? -->
  <%= form_group_tag(wiki.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
   <% end %>


   <% if current_user.admin? || current_user.premium? %>

     <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private topic
          <% end %>
      </div>

    <%end%>

   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>

 <% end %>

app/views/wikis/_wiki.html.erb
<h1><%= @wiki.title %></h1>

<% if policy(@wiki).update?%>
  <%= link_to "Edit wiki", edit_wiki_path, class: 'btn btn-success' %>
  <%= link_to "Delete wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
<%end%>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= markdown(@wiki.body) %></p>
<!-- DISPLAY wiki POSTS -->
    <!-- <%= render @wiki.comments %> -->

  </div>
  <div class="col-md-4">
    <%= link_to "New Comment", new_wiki_post_path(@wiki), class: 'btn btn-success' %>
  </div>


</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">

  <div class="col-md-4">
    <p>Guidelines for Wikis:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>



<% if current_user.admin? || current_user.premium?%>
    <% if collabs = @wiki.collaborators %>
        <ul>
          <% collabs.each do |collab| %>
            <li><%= link_to "X #{collab.user.email}", collab, class: 'btn btn-danger', method: :delete %></li>
          <% end %>
        </ul>
    <%end%>


    <%= form_tag '/collaborators' do %>
        <%= text_field_tag :email %>
        <%= hidden_field_tag :wiki_id, @wiki.id %>

        <%= submit_tag "Invite", class: 'btn btn-success' %>
        <% end %>
<% end %>


  </div>

   <div class="col-md-8">
     <!-- here we specify the resource objects as elements
      to the create action route of the form -->
     <%= render partial: 'form', locals: {wiki: @wiki } %>
  </div>

</div>

app/views/wikis/index.html.erb
<h1>Wiki Feed</h1>

<div class="row">

  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">

        <div class="media-body">
          <h4 class="media-heading">
             <%= link_to wiki.title, wiki%>
          </h4>
          <small>
            <%= wiki.body%>
          </small>
        </div>

      </div>
    <% end %>
  </div>

  <div class="col-md-4">

    <% if user_signed_in? %>
     <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success'%>
   <%end%>
  </div>

</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">

  <div class="col-md-4">
    <p>Guidelines for Wikis:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>

  </div>

   <div class="col-md-8">
     <!-- here we specify the resource objects as elements
      to the create action route of the form -->
      <%= render partial: 'form', locals: {wiki: @wiki } %>


  </div>

</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>


<div class="row">
  <div class="col-md-8">
    <h4><%= markdown(@wiki.body) %></h4>

  </div>


  <div class="col-md-4">
    <%if policy(@wiki).update?%>
      <%= link_to "edit wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "delete wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
    <%end%>
  </div>



</div>