config/routes.rb
Rails.application.routes.draw do



  resources :charges, only: [:new, :create, :update]

  resources :wikis

  resources :collaborators, only: [:create, :destroy]




# name of the controller(usually plural form of resource + controller)
  resources :registration_downgrades, only: [:create]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <ul class="nav nav-tabs">
          <li><%= link_to "Blocipedia", root_path %></li>
          <li><%= link_to "Wikis", wikis_path %></li>



          <div class="pull-right">
            <%if user_signed_in?%>

                  <div class="pull-right">
                    <%= link_to "#{current_user.email}", edit_user_registration_path %><br/> <%= link_to "Sign Out", destroy_user_session_path(current_user), method: :delete %>
                  </div>

            <%else%>
              <%= link_to "Sign In", new_user_session_path %>
              <%= link_to "Sign Up", new_user_registration_path %>
            <%end%>
          </div>
        </ul>


        <!--  ADD NOTICE MESSAGES USING FLASH HASH FROM NEW VIEW.-->
            <% if flash[:notice] %>
               <div class="alert alert-success">
                 <button type="button" class="close" data-dismiss="alert">&times;</button>
                 <%= flash[:notice] %>
               </div>
             <% elsif flash[:alert] %>
               <div class="alert alert-warning">
                 <button type="button" class="close" data-dismiss="alert">&times;</button>
                 <%= flash[:alert] %>
               </div>
             <% end %>

    <%= yield %>
  </body>
</html>